# Generated by Django 3.2 on 2021-04-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProject', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=2)),
                ('assign', models.CharField(max_length=100)),
                ('status', models.CharField(default='Not Done', max_length=100)),
            ],
        ),
    ]
